name: "Develop"

on:
  push:
    branches:
      - develop

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Show GitVersion
        id: show-gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
      
      - name: Tag commit fullSemVer
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git tag -a ${{ steps.show-gitversion.outputs.fullSemVer }} -m "${{ github.event.head_commit.message }}"
          git push origin ${{ steps.show-gitversion.outputs.fullSemVer }}
        
      