name: "Show GitVersion"

on:
  workflow_dispatch:

jobs:
  show-gitversion:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'
      
      - name: Show GitVersion
        uses: gittools/actions/gitversion/execute@v3.0.0